[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lvaes"
version = "0.0.0"

readme = "README.md"

[options]
package_dir = "src"

[options.packages.find]
where="src"